name: Update Application

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Generate Update Files
        run: powershell -ExecutionPolicy Bypass -File ./build/update.ps1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v$(date +%Y%m%d)
          release_title: 'Application Update $(date +%Y%m%d)'
          prerelease_name: 'pre'
          body: |
            ## [Source](https://github.com/YourRepository/YourProject/releases/tag/v$(date +%Y%m%d))
            Y4:0
